Add operator and aide-ds pod limits
openshift/file-integrity-operator pull request #176
Opened 2021-05-18 23:39 UTC by mrogers950

2021-05-19 07:21 UTC, JAORMX commented on pkg/controller/fileintegrity/fileintegrity_controller.go
> +									corev1.ResourceCPU:    resource.MustParse("100m"),
let's reduce the requests to:
```
 memory: 10Mi
 cpu: 10m
```

That'll make it more likely that the kubelet can schedule this. If it's too high sometimes it happens that the kubelet is unable to schedule the pod at all.

2021-05-20 01:35 UTC, mrogers950 commented
/test all

2021-05-20 02:50 UTC, JAORMX requested changes

2021-05-20 02:50 UTC, JAORMX commented on pkg/controller/fileintegrity/fileintegrity_controller.go
> +									corev1.ResourceCPU:    resource.MustParse("400m"),
for the SNO case, I'd rather limit this too 100m. It might make integrity checks slower, but it allows us for better bin-packing. e.g. platform or control plane components get to take less space.

2021-05-20 02:50 UTC, JAORMX commented on deploy/operator.yaml
> +              memory: "20Mi"
The controllers are mostly sleeping. I suggest lowering this to 10Mi.

2021-05-20 14:29 UTC, JAORMX approved these changes
/lgtm

2021-05-20 19:20 UTC, mrogers950 commented
The compressed log scan took quite a bit longer it seems
/retest

2021-05-21 04:21 UTC, JAORMX commented
If it takes too much of an impact we should increase the limit again then :/

2021-05-24 05:17 UTC, JAORMX commented
/test all

2021-05-24 12:12 UTC, merged