WIP: multiple-reinit fixes
openshift/file-integrity-operator pull request #190
Opened 2021-08-11 01:14 UTC by mrogers950

2021-08-16 18:55 UTC, mrogers950 commented
/retest

2021-08-17 00:11 UTC, mrogers950 commented
@jhrozek @JAORMX please review when you can!

2021-08-17 21:18 UTC, mrogers950 commented
/retest

2021-08-18 15:45 UTC, JAORMX commented on pkg/controller/status/status_controller.go
> +var statusRequeue = time.Second * 10
why the 10 second change?

2021-08-18 15:46 UTC, JAORMX reviewed
overall this lgtm, just got one question, but I'll give this another review anyway.

2021-08-18 15:55 UTC, mrogers950 commented on pkg/controller/status/status_controller.go
> +var statusRequeue = time.Second * 10
TBH I forgot I changed this while debugging. The important piece to this was that I added the re-queue on successful status update back. When I removed it some patches ago, I thought it was affecting things differently.

2021-08-18 15:57 UTC, JAORMX requested changes

2021-08-18 15:57 UTC, JAORMX commented on pkg/controller/fileintegrity/fileintegrity_controller.go
> +	nodeToReinit, forceReinit := instance.Annotations[common.AideDatabaseReinitAnnotationKey]
let's handle a case where `nodeToReinit` is an empty string (as it used to be). This way, in case there's a FIO upgrade in the middle of a re-init, we won't get this funky case. This could also happen if a user (for some weird reason) changes the value of the label to empty string.

2021-08-18 15:57 UTC, JAORMX commented on pkg/controller/fileintegrity/fileintegrity_controller.go
> +	err := r.client.Get(context.TODO(), types.NamespacedName{Name: node}, n)
let's handle if this call returns NotFound. This way we can dismiss a Node that has been scaled down and no longer exists.

2021-08-18 17:54 UTC, mrogers950 commented on pkg/controller/fileintegrity/fileintegrity_controller.go
> +	nodeToReinit, forceReinit := instance.Annotations[common.AideDatabaseReinitAnnotationKey]
that's handled inside createReinitDaemonSet(), the result of an empty string for node there is that you get a re-init ds that applies to all FI nodes, as before.

2021-08-18 18:26 UTC, mrogers950 commented on pkg/controller/fileintegrity/fileintegrity_controller.go
> +	err := r.client.Get(context.TODO(), types.NamespacedName{Name: node}, n)
Done.

2021-08-18 21:15 UTC, mrogers950 commented
/retest

2021-08-19 06:10 UTC, JAORMX requested changes

2021-08-19 06:10 UTC, JAORMX commented on pkg/controller/status/status_controller.go
> +		err = r.client.Get(context.TODO(), types.NamespacedName{Name: dsName, Namespace: common.FileIntegrityNamespace}, ds)
don't we have relevant labels we could use to filter these? In that case you could just do a `List` call and not attempt to do a call per node, which would be very costly in a very big cluster.

2021-08-19 06:10 UTC, JAORMX commented on pkg/controller/fileintegrity/fileintegrity_controller.go
> +	nodeToReinit, forceReinit := instance.Annotations[common.AideDatabaseReinitAnnotationKey]
Got it!

2021-08-19 06:10 UTC, JAORMX commented on pkg/controller/fileintegrity/fileintegrity_controller.go
> +	}
Moving this block to its own function or commenting this a little more would help the reader know that having an empty nodeName is fine and an expected behavior.

2021-08-19 09:54 UTC, jhrozek approved these changes
I think the PR looks good as-is, only one question:
is the per-node re-init something you wanted to have documented as an external usage or only for the internal use when a node is initializing? If the former, then please update README.md and ask the docs writers to document this. But I'm not sure it is needed honestly.

2021-08-19 10:04 UTC, JAORMX commented
@jhrozek  I think it's an implementation detail. What users should care about is the reinitialization annotation, not the mechanism that goes behind it. But... maybe having developer docs would help us in the future maintenance-wise.

2021-08-19 11:30 UTC, merged