Bug 1999186: Add MCO and CVO related config excludes
openshift/file-integrity-operator pull request #195
Opened 2021-08-30 16:57 UTC by mrogers950

@JAORMX

2021-08-31 05:58 UTC, JAORMX requested changes

2021-08-31 05:58 UTC, JAORMX commented on pkg/controller/fileintegrity/config_defaults.go
> +!/hostroot/etc/cvo
I don't think we should fully exclude these, but at least we should be checking that the appropriate permissions are kept.

2021-08-31 05:58 UTC, JAORMX commented on pkg/controller/fileintegrity/config_defaults.go
> +!/hostroot/etc/pki/ca-trust/extracted/java
isn't this merely a PKCS12 file? that one shouldn't change as often.

2021-09-01 14:02 UTC, mrogers950 commented on pkg/controller/fileintegrity/config_defaults.go
> +!/hostroot/etc/cvo
Actually I think there's a regex pattern I can use to still watch for weird stuff in the directory and omit the dynamic files. Gotta look into it some more.

2021-09-02 11:20 UTC, JAORMX commented
/bugzilla refresh

2021-09-03 18:22 UTC, mrogers950 commented
@JAORMX I've updated it to a more specific exclude, so we should have better coverage with this iteration.

2021-09-03 20:11 UTC, JAORMX commented
/lgtm
/approve

2021-09-03 20:13 UTC, merged