Add initialDelay
openshift/file-integrity-operator pull request #303
Opened 2023-02-15 23:02 UTC by Vincent056

We added `initalDelay` option to FileIntegrity CRD to allow users to specify the initial delay before the first scan is run. This is useful for environments where the operator is deployed before the cluster is fully ready.

2023-02-16 15:58 UTC, rhmdnd requested changes
Thanks for getting this proposed!

A few suggestions inline along with a recommendation to make the feature non-blocking.

2023-02-16 15:58 UTC, rhmdnd commented on config/crd/bases/fileintegrity.openshift.io_fileintegrities.yaml
> +                    description: InitalDelaySeconds is the number of seconds to wait
nit: InitialDelaySeconds

"first scan. It"

2023-02-16 15:58 UTC, rhmdnd commented on pkg/controller/fileintegrity/fileintegrity_controller.go
> +			reqLogger.Info("InitialDelaySeconds not set, creating deamonset now")
nit: `daemonSet` to be consistent with the log above.

2023-02-16 15:58 UTC, rhmdnd commented on tests/e2e/e2e_test.go
> +func TestFileIntegrityInitalDelay(t *testing.T) {
nit: Initial*

2023-02-16 15:58 UTC, rhmdnd commented on pkg/controller/fileintegrity/fileintegrity_controller.go
> +			time.Sleep(time.Duration(instance.Spec.Config.InitialDelay) * time.Second)
Based on my testing - this is a blocking operation and could to confusion with multiple file integrity resources.

I tested this by creating two different scans:

```$ cat master-fio.yaml
apiVersion: fileintegrity.openshift.io/v1alpha1
kind: FileIntegrity
metadata:
  name: master-fileintegrity
  namespace: openshift-file-integrity
spec:
  nodeSelector:
      node-role.kubernetes.io/master: ""
  config:
      name: master-aide-conf
      namespace: openshift-file-integrity
      initialDelay: 120
$ cat worker-fio.yaml
apiVersion: fileintegrity.openshift.io/v1alpha1
kind: FileIntegrity
metadata:
  name: worker-fileintegrity
  namespace: openshift-file-integrity
spec:
  nodeSelector:
      node-role.kubernetes.io/worker: ""
  config:
      name: worker-aide-conf
      namespace: openshift-file-integrity
      initialDelay: 120
```

I created them at the same time. I expect that the daemonSets for each would be available at the same time (since they use the same initial delay and I created them around the same time).

What I observed is that the timer for the second file integrity starts *after* the first is created because the reconcile loop is sleeping.

```
NAME                                       DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                     AGE
daemonset.apps/aide-master-fileintegrity   3         3         3       3            3           node-role.kubernetes.io/master=   2m6s
daemonset.apps/aide-worker-fileintegrity   2         2         2       2            2           node-role.kubernetes.io/worker=   6s
```

Is it possible to re-queue the request and determine this based on the request timestamp?

2023-02-16 17:02 UTC, rhmdnd commented on pkg/controller/fileintegrity/fileintegrity_controller.go
> +			time.Sleep(time.Duration(instance.Spec.Config.InitialDelay) * time.Second)
I used the following to make this a non-blocking operation.

```
 $ git d pkg/controller/
diff --git a/pkg/controller/fileintegrity/fileintegrity_controller.go b/pkg/controller/fileintegrity/fileintegrity_controller.go
index c18a49d8..37b7cb5a 100644
--- a/pkg/controller/fileintegrity/fileintegrity_controller.go
+++ b/pkg/controller/fileintegrity/fileintegrity_controller.go
@@ -440,13 +440,16 @@ func (r *FileIntegrityReconciler) FileIntegrityControllerReconcile(request recon
                        return reconcile.Result{}, legacyDeleteErr
                }

-               // check if we have initialDelay set
-               if instance.Spec.Config.InitialDelay == 0 {
-                       reqLogger.Info("InitialDelaySeconds not set, creating deamonset now")
-               } else {
-                       // sleep for the initial delay
-                       reqLogger.Info("InitialDelaySeconds set, sleeping", "InitialDelaySeconds", instance.Spec.Config.InitialDelay)
-                       time.Sleep(time.Duration(instance.Spec.Config.InitialDelay) * time.Second)
+               // Check if we're past the initial delay timer by evaluating
+               // the time since creation.
+               n := time.Now()
+               d := n.Sub(instance.GetCreationTimestamp().Time)
+
+               if d.Seconds() < float64(instance.Spec.Config.InitialDelay) {
+                       s := fmt.Sprintf("Re-queuing request for %s because elapsed time since creation (%f seconds) hasn't exceeded InitialDelay of %d seconds", instance.Name, d.Seconds(), instance.Spec.Config.InitialDelay)
+                       reqLogger.Info(s)
+                       // requeue the request
+                       return reconcile.Result{Requeue: true}, nil
                }

                reqLogger.Info("Creating daemonSet", "DaemonSet", daemonSetName)

```

2023-02-16 18:16 UTC, Vincent056 commented
> Thanks for getting this proposed!
> 
> A few suggestions inline along with a recommendation to make the feature non-blocking.

Thanks for the throughout review, let me address those issues

2023-02-17 06:46 UTC, Vincent056 commented on pkg/controller/fileintegrity/fileintegrity_controller.go
> +			time.Sleep(time.Duration(instance.Spec.Config.InitialDelay) * time.Second)
that's a good catch, thanks for it, this works now!

2023-02-17 08:49 UTC, jhrozek commented on pkg/controller/fileintegrity/fileintegrity_controller.go
> +		if d.Seconds() < float64(instance.Spec.Config.InitialDelay) {
I think it would be more idiomatic to try to use the `time.Before()` or `time.After` methods.
Something like:
```
shouldScheduleAt := instance.CreationTimestamp.Time.Add(instance.Spec.Config.InitialDelay)
if time.Now().Before(shouldScheduleAt) {
 // reconcile
}
```

2023-02-17 09:14 UTC, Vincent056 commented on pkg/controller/fileintegrity/fileintegrity_controller.go
> +		if d.Seconds() < float64(instance.Spec.Config.InitialDelay) {
Thanks for the review, this makes sense, just updated the code

2023-02-17 09:15 UTC, Vincent056 commented
Has success e2e run on my local cluster, it looks like we have some issues with must gather

2023-02-17 14:53 UTC, rhmdnd reviewed
Code changes look good. Just have to figure out the e2e issues.

2023-02-17 22:39 UTC, Vincent056 commented
/retest

2023-02-20 20:35 UTC, Vincent056 commented
/retest

2023-02-23 14:58 UTC, Vincent056 commented
/retest

2023-02-23 14:59 UTC, xiaojiey commented
Verification pass with 4.13.0-0.nightly-2023-02-23-000625 and code in the PR:
1. deploy FIO with code in the PR
2. Create fileintegrity with initialDelay set to 300, and check results:
$ oc create cm worker-aide-conf --from-file=aide-conf=aide.conf.rhel8
configmap/worker-aide-conf created
$ oc create cm master-aide-conf --from-file=aide-conf=aide.conf.rhel8.1
configmap/master-aide-conf created
$ oc apply -f -<<EOF
---
apiVersion: fileintegrity.openshift.io/v1alpha1
kind: FileIntegrity
metadata:
  name: worker-fileintegrity
  namespace: openshift-file-integrity
spec:
  nodeSelector:
      node-role.kubernetes.io/worker: ""
  config:
      name: worker-aide-conf
      namespace: openshift-file-integrity
      initialDelay: 300
      gracePeriod: 300
---
apiVersion: fileintegrity.openshift.io/v1alpha1
kind: FileIntegrity
metadata:
  name: master-fileintegrity
  namespace: openshift-file-integrity
spec:
  nodeSelector:
      node-role.kubernetes.io/master: ""
  config:
      name: master-aide-conf
      namespace: openshift-file-integrity
      initialDelay: 300
      gracePeriod: 300
EOF
fileintegrity.fileintegrity.openshift.io/worker-fileintegrity created
fileintegrity.fileintegrity.openshift.io/master-fileintegrity created
$ oc get daemonsets.apps  -w
^C
$ oc get fileintegrity
NAME                   AGE
master-fileintegrity   4m42s
worker-fileintegrity   4m43s
$ oc get daemonsets.apps  -w
NAME                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                     AGE
aide-worker-fileintegrity   0         0         0       0            0           node-role.kubernetes.io/worker=   0s
aide-worker-fileintegrity   3         3         0       3            0           node-role.kubernetes.io/worker=   0s
aide-master-fileintegrity   0         0         0       0            0           node-role.kubernetes.io/master=   0s
aide-master-fileintegrity   3         3         0       3            0           node-role.kubernetes.io/master=   0s
^C
$ oc get fileintegrity
NAME                   AGE
master-fileintegrity   5m4s
worker-fileintegrity   5m5s
$ oc get daemonsets.apps  -w
NAME                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                     AGE
aide-master-fileintegrity   3         3         1       3            1           node-role.kubernetes.io/master=   8s
aide-worker-fileintegrity   3         3         0       3            0           node-role.kubernetes.io/worker=   9s
aide-worker-fileintegrity   3         3         1       3            1           node-role.kubernetes.io/worker=   17s
aide-worker-fileintegrity   3         3         2       3            2           node-role.kubernetes.io/worker=   19s
aide-worker-fileintegrity   3         3         3       3            3           node-role.kubernetes.io/worker=   19s
aide-master-fileintegrity   3         3         2       3            2           node-role.kubernetes.io/master=   20s
aide-master-fileintegrity   3         3         3       3            3           node-role.kubernetes.io/master=   21s
^C
$ oc get pod
NAME                                      READY   STATUS    RESTARTS      AGE
aide-master-fileintegrity-8d5n6           1/1     Running   0             42s
aide-master-fileintegrity-qhqsp           1/1     Running   0             42s
aide-master-fileintegrity-tdrxn           1/1     Running   0             42s
aide-worker-fileintegrity-8vt5t           1/1     Running   0             43s
aide-worker-fileintegrity-rbzpp           1/1     Running   0             43s
aide-worker-fileintegrity-wgrcs           1/1     Running   0             43s
file-integrity-operator-9dd874f46-888hn   1/1     Running   1 (34m ago)   35m
$ oc logs pod/aide-master-fileintegrity-8d5n6 --all-containers 
2023-02-23T14:38:41Z: Starting the AIDE runner daemon
W0223 14:38:41.781706       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2023-02-23T14:38:41Z: running aide check
2023-02-23T14:39:12Z: aide check returned status 0
$ oc get fileintegritynodestatus
NAME                                                                             NODE                                                        STATUS
master-fileintegrity-xiyuan-23-pr-2f4zq-master-0.c.openshift-qe.internal         xiyuan-23-pr-2f4zq-master-0.c.openshift-qe.internal         Succeeded
master-fileintegrity-xiyuan-23-pr-2f4zq-master-1.c.openshift-qe.internal         xiyuan-23-pr-2f4zq-master-1.c.openshift-qe.internal         Succeeded
master-fileintegrity-xiyuan-23-pr-2f4zq-master-2.c.openshift-qe.internal         xiyuan-23-pr-2f4zq-master-2.c.openshift-qe.internal         Succeeded
worker-fileintegrity-xiyuan-23-pr-2f4zq-worker-a-ncwxc.c.openshift-qe.internal   xiyuan-23-pr-2f4zq-worker-a-ncwxc.c.openshift-qe.internal   Succeeded
worker-fileintegrity-xiyuan-23-pr-2f4zq-worker-b-dc7q4.c.openshift-qe.internal   xiyuan-23-pr-2f4zq-worker-b-dc7q4.c.openshift-qe.internal   Succeeded
worker-fileintegrity-xiyuan-23-pr-2f4zq-worker-c-vc7hc.c.openshift-qe.internal   xiyuan-23-pr-2f4zq-worker-c-vc7hc.c.openshift-qe.internal   Succeeded

2023-02-23 14:59 UTC, xiaojiey commented
/label qe-app-approved

2023-02-28 22:05 UTC, rhmdnd approved these changes
/lgtm

Thanks, Vincent!

2023-02-28 22:10 UTC, merged