AIDE migration
openshift/file-integrity-operator pull request #537
Opened 2024-07-02 14:10 UTC by Vincent056

This PR adds ability to run aide 0.18 config checks and migration.

The aide0.18 will be complied as a CGO library and used by FIO, we will try to see if we can perform the migration if a user defined config is being detected. We will issue warning messages in the log, and have a failed annotation key in the FIO instance if we are not able to pre migrate the config.

 Annotation keys added:

```
	// AideConfigMigrationIgnoreAnnotationKey tells us to ignore the deprecated config options
	AideConfigMigrationIgnoreAnnotationKey = "file-integrity.openshift.io/migration-ignore-deprecation"
	// AideConfigMigrationFailedAnnotationKey tells us that the migration failed
	AideConfigAutoMigrationFailedAnnotationKey = "file-integrity.openshift.io/migration-failed"
	// AideConfigMigrationCheckDisabledAnnotationKey tells us that the migration check is disabled
	AideConfigMigrationCheckDisabledAnnotationKey = "file-integrity.openshift.io/migration-check-disabled"
```

2024-07-09 14:54 UTC, Vincent056 commented
/retest

2024-07-10 13:13 UTC, rhmdnd commented on pkg/controller/fileintegrity/config_defaults.go
> +!/hostroot/etc/mco/internal-registry-pull-secret.json$
Interesting.. I wonder if I'm seeing e2e error because of this, too.

2024-07-10 13:19 UTC, rhmdnd commented on pkg/controller/fileintegrity/config_defaults.go
> +!/hostroot/etc/mco/internal-registry-pull-secret.json$
Pulled this out into another change to see if we can get a clean run in isolation.

https://github.com/openshift/file-integrity-operator/pull/541

2024-07-12 18:45 UTC, Vincent056 commented
we will save migrate config in:

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: example-fileintegrity
  namespace: openshift-file-integrity
  uid: 3e68694f-fed1-403f-805f-813eec85ff38
  resourceVersion: '68362036'
  creationTimestamp: '2024-06-28T06:22:38Z'
  labels:
    file-integrity.openshift.io/aide-conf: ''
    file-integrity.openshift.io/owner: example-fileintegrity
  annotations:
    kubernetes.io/description: hi
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2024-07-12T06:37:37Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubernetes.io/description': {}
    - manager: file-integrity-operator
      operation: Update
      apiVersion: v1
      time: '2024-07-12T18:35:21Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:aide-0.18.conf': {}
          'f:aide.conf': {}
        'f:metadata':
          'f:labels':
            .: {}
            'f:file-integrity.openshift.io/aide-conf': {}
            'f:file-integrity.openshift.io/owner': {}
data:
  aide-0.18.conf: |-
    @@define DBDIR /hostroot/etc/kubernetes
    @@define LOGDIR /hostroot/etc/kubernetes
    database_in=file:@@{DBDIR}/aide.db.gz
    database_out=file:@@{DBDIR}/aide.db.gz.new
    gzip_dbout=yes
    log_level=notice
    report_level=added_removed_attributes
    report_url=file:@@{LOGDIR}/aide.log.new
    report_url=stdoutx
    PERMS = p+u+g+acl+selinux+xattrs
    CONTENTEX=sha512+ftype+p+u+g+n+acl+selinux+xattrs

    /hostroot/boot/        CONTENTEX
    /hostroot/root/\..* PERMS
    /hostroot/root/   CONTENTEX
    !/hostroot/root/\.kube
    !/hostroot/usr/src/
    !/hostroot/usr/tmp/

    /hostroot/usr/    CONTENTEX

    # OpenShift specific excludes
    !/hostroot/opt/
    !/hostroot/var
    !/hostroot/etc/NetworkManager/system-connections/
    !/hostroot/etc/mtab$
    !/hostroot/etc/.*~
    !/hostroot/etc/kubernetes/static-pod-resources
    !/hostroot/etc/kubernetes/test
    !/hostroot/etc/kubernetes/aide.*
    !/hostroot/etc/kubernetes/manifests
    !/hostroot/etc/kubernetes/kubelet-ca.crt
    !/hostroot/etc/docker/certs.d
    !/hostroot/etc/selinux/targeted
    !/hostroot/etc/openvswitch/conf.db
    !/hostroot/etc/kubernetes/cni/net.d
    !/hostroot/etc/kubernetes/cni/net.d/*
    !/hostroot/etc/machine-config-daemon/currentconfig$
    !/hostroot/etc/machine-config-daemon/node-annotation.json*
    !/hostroot/etc/pki/ca-trust/extracted/java/cacerts$
    !/hostroot/etc/cvo/updatepayloads
    !/hostroot/etc/cni/multus/certs
    !/hostroot/etc/kubernetes/compliance-operator
    !/hostroot/etc/kubernetes/node-feature-discovery

    # Catch everything else in /etc
    /hostroot/etc/    CONTENTEX
  aide.conf: |-
    @@define DBDIR /hostroot/etc/kubernetes
    @@define LOGDIR /hostroot/etc/kubernetes
    database=file:@@{DBDIR}/aide.db.gz
    database_out=file:@@{DBDIR}/aide.db.gz.new
    gzip_dbout=yes
    verbose=6
    report_url=file:@@{LOGDIR}/aide.log.new
    report_url=stdoutx
    PERMS = p+u+g+acl+selinux+xattrs
    CONTENT_EX = sha512+ftype+p+u+g+n+acl+selinux+xattrs

    /hostroot/boot/        CONTENT_EX
    /hostroot/root/\..* PERMS
    /hostroot/root/   CONTENT_EX
    !/hostroot/root/\.kube
    !/hostroot/usr/src/
    !/hostroot/usr/tmp/

    /hostroot/usr/    CONTENT_EX

    # OpenShift specific excludes
    !/hostroot/opt/
    !/hostroot/var
    !/hostroot/etc/NetworkManager/system-connections/
    !/hostroot/etc/mtab$
    !/hostroot/etc/.*~
    !/hostroot/etc/kubernetes/static-pod-resources
    !/hostroot/etc/kubernetes/test
    !/hostroot/etc/kubernetes/aide.*
    !/hostroot/etc/kubernetes/manifests
    !/hostroot/etc/kubernetes/kubelet-ca.crt
    !/hostroot/etc/docker/certs.d
    !/hostroot/etc/selinux/targeted
    !/hostroot/etc/openvswitch/conf.db
    !/hostroot/etc/kubernetes/cni/net.d
    !/hostroot/etc/kubernetes/cni/net.d/*
    !/hostroot/etc/machine-config-daemon/currentconfig$
    !/hostroot/etc/machine-config-daemon/node-annotation.json*
    !/hostroot/etc/pki/ca-trust/extracted/java/cacerts$
    !/hostroot/etc/cvo/updatepayloads
    !/hostroot/etc/cni/multus/certs
    !/hostroot/etc/kubernetes/compliance-operator
    !/hostroot/etc/kubernetes/node-feature-discovery

    # Catch everything else in /etc
    /hostroot/etc/    CONTENT_EX
```

2024-07-12 18:45 UTC, Vincent056 commented
@rhmdnd this should be ready for some reviews

2024-07-12 21:29 UTC, rhmdnd requested changes
Took an initial pass, but I still need to come back and look through the config map controller and file integrity controller logic.

Posting the feedback I have for now.

2024-07-12 21:29 UTC, rhmdnd commented on Dockerfile.ci
> +    cp autoconf-archive/m4/*.m4 /usr/share/aclocal/
Is this a dependency for building AIDE 0.18?

2024-07-12 21:29 UTC, rhmdnd commented on Makefile
> +	cd aide && \
We have a `build` directory where we stash other related tools like `controller-gen` and `kustomize`. We could keep the entire repository in there so it gets cleaned up using `make clean`. Otherwise, we might need to go in and clean it up manually if we encounter a build failure.

2024-07-12 21:29 UTC, rhmdnd commented on Makefile
> +	cp aide/aide ./build/bin/aide-0.18 && \
+1 to putting this in the build directory

2024-07-12 21:29 UTC, rhmdnd commented on cmd/manager/daemon.go
> +
nit: extra newline?

2024-07-12 21:29 UTC, rhmdnd commented on cmd/manager/loops.go
> +			DBG("migrateLoop cancelled by the main routine!")
This error will be written to logs, right? If so, we might want to think of a way to make the language less specific to the implementation details of the code. As a kubernetes administrator, how would I interpret this if I don't know the code? What do I need to do instead?

2024-07-12 21:29 UTC, rhmdnd commented on cmd/manager/loops.go
> +				LOG("AIDE migration check passed")
We could explicitly say that the configuration we checked is safe to run using AIDE 0.18.0 (and that we'll just do that for users automatically or something).

2024-07-12 21:29 UTC, rhmdnd commented on cmd/manager/loops.go
> +				logAndTryReportingDaemonError(migrateCtx, rt, conf, fmt.Sprintf("Detected error config during the migration check: %s",
Similar comment as above, where we could say explicitly that we can't run this configuration with AIDE 0.18.0.

Does the migration check give us a line number that's causing the error? If so, we could give that to users in the log output so that know what they need to go change. That might be a stretch, but I'm just trying to think of ways to get users specific information that helps them work through the issue if we can't do it for them.

2024-07-12 21:29 UTC, rhmdnd commented on cmd/manager/loops.go
> +				if err := reportError(migrateCtx, fmt.Sprintf("Detected error config during the migration check: %s",
nit: We could share the fmt.Sprintf between this line and 104 since it's the same.

2024-07-12 21:29 UTC, rhmdnd commented on cmd/manager/loops.go
> +				if err := reportError(ctx, fmt.Sprintf("Error running migration check: %s",
Similar comment as above on line 106.

2024-07-12 21:29 UTC, rhmdnd commented on tests/e2e/e2e_test.go
> +	}
Nice - thanks for adding this. So the remaining bit to test would be running AIDE 0.18.0, yeah? At this point, the test is assertion the configuration *should* work with 0.18.0, but we're still running 0.16.0.

2024-07-13 04:01 UTC, Vincent056 commented on Dockerfile.ci
> +    cp autoconf-archive/m4/*.m4 /usr/share/aclocal/
yes, I think rhel might has rpm for this, but this builder does not

2024-07-19 03:20 UTC, Vincent056 commented on tests/e2e/e2e_test.go
> +	}
correct

2024-07-19 03:23 UTC, Vincent056 commented
> Took an initial pass, but I still need to come back and look through the config map controller and file integrity controller logic.
> 
> Posting the feedback I have for now.

thanks for the detail reviews!

2024-07-23 01:08 UTC, Vincent056 commented
/retest

2024-07-23 05:08 UTC, Vincent056 commented
/retest

2024-07-23 20:56 UTC, rhmdnd requested changes
Looking good - a few more comments inline now that I've had more time to walk through the controller code and the tests.

2024-07-23 20:56 UTC, rhmdnd commented on build/Dockerfile
> +RUN make aide-0.18
Another alternative we talked about earlier was to build this using a separate ubi8 base image container and then copying it over, too.

Or, at least in this case, we could just copy it out of the fedora 40 image and see how that works.

2024-07-23 20:56 UTC, rhmdnd commented on build/Dockerfile
> +COPY --from=builder /go/src/github.com/openshift/file-integrity-operator/build/bin/aide-0.18 /usr/sbin/aide-0.18
Then we don't need to pollute the builder container image with utilities and code unrelated to golang, or building FIO.

2024-07-23 20:56 UTC, rhmdnd commented on tests/e2e/helpers.go
I think we'll also need to update the default AIDE configuration.

https://github.com/openshift/file-integrity-operator/blob/master/pkg/controller/fileintegrity/config_defaults.go#L15-L61

The way I understand the current logic is that FIO will continue to lay down AIDE configurations that are not compatible with 0.18.0. I think we'll want to change that as soon as possible, so long as the default AIDE configuration for 0.18.0 we want to use works on 0.16.0. That way we don't have the maintain the migration logic any longer than we absolutely have to.

2024-07-23 20:56 UTC, rhmdnd commented on tests/e2e/helpers.go
> -	// Append operatorPods to pods
nit: unrelated change?

2024-07-23 20:56 UTC, rhmdnd commented on tests/e2e/helpers.go
> +func waitForFIMigrationErrAnnotation(t *testing.T, f *framework.Framework, namespace, name, expectedMessage string) error {
nit: we could use this as an assertion and not have to deal with checking the error output in the caller to fail the test, making it more of an assertion.

```go
func assertAIDEMigrationEmitsAnAlert(...)
```

And then a similar one below:

```go
func assertAIDEMigrationIsSuccessful(...)
```

But, I acknowledge this would be potentially different from existing conventions and we could do that in a separate PR if we decide to make that change across the entire functional test suite.

2024-07-24 17:17 UTC, Vincent056 commented on pkg/controller/fileintegrity/config.go
> +					return "", ignoredLines, fmt.Errorf("Deprecated option found: %s, please use %s separately", line, nonReplaceableKeys[key])
that's a good catch, the map should be ignore_list to all of those optios

2024-07-24 17:17 UTC, Vincent056 commented on pkg/controller/fileintegrity/config.go
> +					return "", ignoredLines, fmt.Errorf("Deprecated option found: %s, please use %s separately", line, nonReplaceableKeys[key])
https://github.com/aide/aide/blob/8ef6931719315a5f44cf6be11ccf73435822e2fe/doc/aide.conf.5#L360

2024-07-24 17:18 UTC, Vincent056 commented on pkg/controller/fileintegrity/config.go
> +					return "", ignoredLines, fmt.Errorf("Deprecated option found: %s, please use %s separately", line, nonReplaceableKeys[key])
in other word, ignore_list should replaced by
```
"report_ignore_added_attrs", "report_ignore_removed_attrs", "report_ignore_changed_attrs","report_ignore_e2fsattrs"
```

2024-12-23 00:01 UTC, closed without merging