Bump up dependency
openshift/file-integrity-operator pull request #543
Opened 2024-07-15 20:17 UTC by Vincent056

Let's bump up dependency in one place to fix CI

2024-07-15 23:18 UTC, Vincent056 commented
/retest

2024-07-17 06:27 UTC, Vincent056 commented
https://github.com/openshift/release/pull/54443 has to merge to fix some of CI failures

2024-07-18 01:16 UTC, Vincent056 commented
/retest

2024-07-18 16:24 UTC, rhmdnd commented on cmd/manager/operator.go
> +			fmt.Println("Secret not found - restarting, as the service may have just been created")
We should try using logging for these instead of printing to stdout for consistency.

2024-07-18 22:33 UTC, Vincent056 commented
/retest

2024-07-19 02:25 UTC, rhmdnd commented on cmd/manager/operator.go
> +			log.Error(err, "Error retrieving secret")
Will this just keep looping like the case above?

2024-07-19 02:51 UTC, Vincent056 commented on cmd/manager/operator.go
> +			log.Error(err, "Error retrieving secret")
that's a good point, I think the error should actually be returned, because we would want to retry here, didn't catch this while reviewing https://github.com/ComplianceAsCode/compliance-operator/pull/491/files#diff-51bd220db414457ea4470ea5d71465bd07e1c789d156c0104e1fce2f3ddbcb1aR771

2024-07-19 19:30 UTC, rhmdnd requested changes
A few suggestions inline. Thanks!

2024-07-19 19:30 UTC, rhmdnd commented on config/rbac/metrics_secret.yaml
> +  namespace: security-profiles-operator
This should be updated to use `file-integrity-operator`, I think.

2024-07-19 19:30 UTC, rhmdnd commented on cmd/manager/operator.go
> +						Name: "metrics-token",
Is this token for metrics, or monitoring?

2024-07-19 22:59 UTC, Vincent056 commented on config/rbac/metrics_secret.yaml
> +  namespace: security-profiles-operator
oops let me have that fixed

2024-07-22 15:18 UTC, Vincent056 commented
/retest

2024-07-22 15:19 UTC, Vincent056 commented on cmd/manager/operator.go
> +						Name: "metrics-token",
It is token for metric service account which allowed to view metrics endpoints

2024-07-22 18:18 UTC, rhmdnd commented on cmd/manager/operator.go
> +		log.Error(err, "Error getting secret name for service account")
Another thing we can incorporate here is the name of the secret and service account. Thinking about the information that an administrator would need to fix the issue just by reading the log. Otherwise they'll either need to guess which secret we're implying here or read the code.

I'm ok doing that in a follow up through before the next release.

2024-07-22 18:20 UTC, rhmdnd commented on cmd/manager/operator.go
> +		log.Error(err, "Error getting secret name for service account")
Oh - wait. I see we're removing this entirely in the next commit.

2024-07-22 18:35 UTC, rhmdnd commented on cmd/manager/operator.go
> -	serverNameStr := "metrics." + namespace + ".svc"
One thing I try to be mindful of is reducing the amount of non-functional change lumped into a broader patch, since it can muddy the git log and make it harder to use git has a tool for dissecting historical changes.

However, we can and should make non-functional improvements for readability, maintenance, consistency, etc... but I'm inclined to make those changes in a dedicated commit with clear reasoning for the change outlined in the commit message.

2024-07-22 18:35 UTC, rhmdnd approved these changes
/lgtm

Thank you for working through this mess and getting CI working with updated deps!

2024-07-22 18:38 UTC, rhmdnd commented
Applying additional labels so we can get these dependencies updated. Note that we're going to add some additional functional testing for monitoring in a subsequent patch.

2024-07-22 18:41 UTC, merged